# Form implementation generated from reading ui file 'MenuV2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 300)
        self.MicLevel = QtWidgets.QSlider(parent=Settings)
        self.MicLevel.setGeometry(QtCore.QRect(90, 180, 160, 18))
        self.MicLevel.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.MicLevel.setObjectName("MicLevel")
        self.InputChoice = QtWidgets.QComboBox(parent=Settings)
        self.InputChoice.setGeometry(QtCore.QRect(90, 70, 68, 22))
        self.InputChoice.setObjectName("InputChoice")

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
